import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";

const jetbrains_Mono = JetBrains_Mono({ 
    subsets: ["latin"],
    weight:["100","200","300","400","500","600","700","800"],
    variable: "--font-jetbrainsMono"
}
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrains_Mono.variable}>
        
       
       <div className="w-[70vw] h-[100vh] mx-auto flex flex-col gap-20">
       <Header/>
        {children}

       </div>
       
    </body>
    </html>
  );
}
